# Default values for order.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

container:
  port: 8080

image:
  repository: 250514148096.dkr.ecr.ap-northeast-2.amazonaws.com/backend
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-091b0f283627e6098, subnet-0d616d00a92fdbde8
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}