apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: redis
      volumeMounts:
        - name: bar
          mountPath: "/etc/foo"
          readOnly: true
  volumes:
    - name: bar
      secret:
        secretName: mysecret
        optional: false